platform :ios, '8.0'
inhibit_all_warnings!

def ffpod(name, dirname=nil)
    pod name, :path => "../#{dirname||name}", :inhibit_warnings => false
end

target 'GreenBaby' do
    pod 'AFNetworking'#AFN 网络请求解析
#    pod 'AFNetworking', '~> 2.6.3'
    pod 'Reachability'#网络状况监听
    pod 'iCarousel'
    pod 'Masonry'#AL布局
    pod 'FMDB'#SQLite库管理
    pod 'MBProgressHUD'#菊花
#    pod 'ZBarSDK', '~> 1.3.1'#二维码扫瞄
    pod 'ZBarSDK-hicool'#二维码扫瞄
    pod 'libqrencode'#二维码生成
#    pod 'SDWebImage'
    pod 'SDWebImage/WebP'#需要VPN
    pod 'libwebp'
    pod 'Bugly'#app异常统计
    pod 'BaiduMobStat'#app异常统计

    ffpod 'VendorSDK'
end

post_install do |installer|
    # 修复 Xcode 9 的 Icon 不显示
    installer.aggregate_targets.each do |target|
        copy_pods_resources_path = "Pods/Target Support Files/#{target.name}/#{target.name}-resources.sh"
        string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
        assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --launch-image "${ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME}" --output-partial-info-plist "${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist"'
        text = File.read(copy_pods_resources_path)
        new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
        File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
    end
    
    project = installer.pods_project
    project.build_configurations.each do |configuration|
        # Disable Strict Prototypes
        configuration.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
        # Disable Document Comments
        configuration.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        configuration.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)', '-Wno-unknown-warning-option']
    end
    
    project.targets.each do |target|
        # .a 文件不需要 copy header
        target.headers_build_phase.clear
        
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            
            if target.name == 'SDWebImage'
                # Fix SDWebImage can not find the libwebp.framework's header files.
                config.build_settings['USER_HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
                config.build_settings['USER_HEADER_SEARCH_PATHS'] << '"$(SRCROOT)/Headers/Public/libwebp/libwebp"'
            end
        end
    end
end
